// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoker.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterMethod int32

const (
	RegisterMethod_UNKOWN RegisterMethod = 0
	RegisterMethod_LOCAL  RegisterMethod = 1
	RegisterMethod_GLOBAL RegisterMethod = 2
)

var RegisterMethod_name = map[int32]string{
	0: "UNKOWN",
	1: "LOCAL",
	2: "GLOBAL",
}

var RegisterMethod_value = map[string]int32{
	"UNKOWN": 0,
	"LOCAL":  1,
	"GLOBAL": 2,
}

func (x RegisterMethod) String() string {
	return proto.EnumName(RegisterMethod_name, int32(x))
}

func (RegisterMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{0}
}

type Activity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Activity) Reset()         { *m = Activity{} }
func (m *Activity) String() string { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()    {}
func (*Activity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{0}
}

func (m *Activity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Activity.Unmarshal(m, b)
}
func (m *Activity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Activity.Marshal(b, m, deterministic)
}
func (m *Activity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Activity.Merge(m, src)
}
func (m *Activity) XXX_Size() int {
	return xxx_messageInfo_Activity.Size(m)
}
func (m *Activity) XXX_DiscardUnknown() {
	xxx_messageInfo_Activity.DiscardUnknown(m)
}

var xxx_messageInfo_Activity proto.InternalMessageInfo

func (m *Activity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Activity) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type InvokeRequest struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Target               *Activity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Arg                  string    `protobuf:"bytes,3,opt,name=arg,proto3" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{1}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InvokeRequest) GetTarget() *Activity {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *InvokeRequest) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

type InvokeResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{2}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RegisterRequest struct {
	Username             string         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Method               RegisterMethod `protobuf:"varint,2,opt,name=method,proto3,enum=mee6aas.agent.invoker.v1.RegisterMethod" json:"method,omitempty"`
	Path                 string         `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetMethod() RegisterMethod {
	if m != nil {
		return m.Method
	}
	return RegisterMethod_UNKOWN
}

func (m *RegisterRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("mee6aas.agent.invoker.v1.RegisterMethod", RegisterMethod_name, RegisterMethod_value)
	proto.RegisterType((*Activity)(nil), "mee6aas.agent.invoker.v1.Activity")
	proto.RegisterType((*InvokeRequest)(nil), "mee6aas.agent.invoker.v1.InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "mee6aas.agent.invoker.v1.InvokeResponse")
	proto.RegisterType((*RegisterRequest)(nil), "mee6aas.agent.invoker.v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "mee6aas.agent.invoker.v1.RegisterResponse")
}

func init() { proto.RegisterFile("invoker.proto", fileDescriptor_64215b76ff6c9221) }

var fileDescriptor_64215b76ff6c9221 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x29, 0x7f, 0x2a, 0x8c, 0x01, 0x9b, 0x89, 0x31, 0x0d, 0x27, 0xb3, 0x17, 0x2b, 0x87,
	0x26, 0x80, 0xf1, 0xe0, 0x49, 0xf0, 0x60, 0x8c, 0x15, 0x92, 0x26, 0xc6, 0xc4, 0xc4, 0xc3, 0x82,
	0x93, 0xd2, 0x08, 0x2d, 0xee, 0x2e, 0x4d, 0x38, 0xfb, 0xf9, 0xfc, 0x4e, 0x86, 0x6d, 0x57, 0xe5,
	0x40, 0xe0, 0xf6, 0x66, 0x3a, 0xf3, 0xde, 0xaf, 0xd3, 0x42, 0x33, 0x4e, 0xb2, 0xf4, 0x83, 0x84,
	0xbf, 0x14, 0xa9, 0x4a, 0xd1, 0x5d, 0x10, 0x5d, 0x73, 0x2e, 0x7d, 0x1e, 0x51, 0xa2, 0x7c, 0xf3,
	0x30, 0xeb, 0xb2, 0x2b, 0xa8, 0x0f, 0xa6, 0x2a, 0xce, 0x62, 0xb5, 0x46, 0x84, 0x6a, 0xc2, 0x17,
	0xe4, 0x5a, 0xe7, 0x96, 0xd7, 0x08, 0xb5, 0xc6, 0x53, 0xa8, 0xcd, 0xf9, 0x84, 0xe6, 0x6e, 0x59,
	0x37, 0xf3, 0x82, 0xad, 0xa1, 0xf9, 0xa0, 0x3d, 0x42, 0xfa, 0x5c, 0x91, 0x54, 0xd8, 0x86, 0xfa,
	0x4a, 0x92, 0xf8, 0xb7, 0xfe, 0x5b, 0xe3, 0x0d, 0xd8, 0x8a, 0x8b, 0x88, 0x94, 0xf6, 0x38, 0xee,
	0x31, 0x7f, 0x17, 0x8d, 0x6f, 0x50, 0xc2, 0x62, 0x03, 0x1d, 0xa8, 0x70, 0x11, 0xb9, 0x15, 0x6d,
	0xb9, 0x91, 0xcc, 0x83, 0x96, 0x89, 0x96, 0xcb, 0x34, 0x91, 0x84, 0x67, 0x60, 0x0b, 0x92, 0xab,
	0xb9, 0x2a, 0x92, 0x8b, 0x8a, 0x7d, 0x59, 0x70, 0x12, 0x52, 0x14, 0x4b, 0x45, 0xe2, 0x10, 0xce,
	0x5b, 0xb0, 0x17, 0xa4, 0x66, 0xe9, 0xbb, 0xe6, 0x6c, 0xf5, 0xbc, 0xdd, 0x9c, 0xc6, 0xf6, 0x49,
	0xcf, 0x87, 0xc5, 0xde, 0xe6, 0x80, 0x4b, 0xae, 0x66, 0x05, 0xae, 0xd6, 0x0c, 0xc1, 0xf9, 0x83,
	0xc8, 0x89, 0x3b, 0x7d, 0x68, 0x6d, 0x3b, 0x20, 0x80, 0xfd, 0x3c, 0x7a, 0x1c, 0xbf, 0x8c, 0x9c,
	0x12, 0x36, 0xa0, 0x16, 0x8c, 0xef, 0x06, 0x81, 0x63, 0x6d, 0xda, 0xf7, 0xc1, 0x78, 0x38, 0x08,
	0x9c, 0x72, 0xef, 0xdb, 0x82, 0xa3, 0xfc, 0xcd, 0x05, 0xbe, 0x81, 0x9d, 0x4b, 0xbc, 0xd8, 0x0d,
	0xb9, 0xf5, 0x85, 0xda, 0xde, 0xfe, 0xc1, 0x9c, 0x8e, 0x95, 0x70, 0x0a, 0x75, 0xc3, 0x87, 0x97,
	0xfb, 0xaf, 0x60, 0x22, 0x3a, 0x87, 0x8c, 0x9a, 0x90, 0x61, 0xf5, 0xb5, 0x9c, 0x75, 0x27, 0xb6,
	0xfe, 0x41, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x8b, 0xd3, 0xbf, 0xb1, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvokerClient is the client API for Invoker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvokerClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type invokerClient struct {
	cc *grpc.ClientConn
}

func NewInvokerClient(cc *grpc.ClientConn) InvokerClient {
	return &invokerClient{cc}
}

func (c *invokerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokerClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokerServer is the server API for Invoker service.
type InvokerServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedInvokerServer can be embedded to have forward compatible implementations.
type UnimplementedInvokerServer struct {
}

func (*UnimplementedInvokerServer) Invoke(ctx context.Context, req *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedInvokerServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterInvokerServer(s *grpc.Server, srv InvokerServer) {
	s.RegisterService(&_Invoker_serviceDesc, srv)
}

func _Invoker_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoker_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invoker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mee6aas.agent.invoker.v1.Invoker",
	HandlerType: (*InvokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Invoker_Invoke_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Invoker_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoker.proto",
}
