// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoker.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddMethod int32

const (
	AddMethod_UNKOWN AddMethod = 0
	AddMethod_LOCAL  AddMethod = 1
	AddMethod_GLOBAL AddMethod = 2
)

var AddMethod_name = map[int32]string{
	0: "UNKOWN",
	1: "LOCAL",
	2: "GLOBAL",
}

var AddMethod_value = map[string]int32{
	"UNKOWN": 0,
	"LOCAL":  1,
	"GLOBAL": 2,
}

func (x AddMethod) String() string {
	return proto.EnumName(AddMethod_name, int32(x))
}

func (AddMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{0}
}

type InvokeRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ActName              string   `protobuf:"bytes,2,opt,name=actName,proto3" json:"actName,omitempty"`
	Arg                  string   `protobuf:"bytes,3,opt,name=arg,proto3" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{0}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *InvokeRequest) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *InvokeRequest) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

type InvokeResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{1}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type AddRequest struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ActName              string    `protobuf:"bytes,2,opt,name=actName,proto3" json:"actName,omitempty"`
	Method               AddMethod `protobuf:"varint,3,opt,name=method,proto3,enum=mee6aas.agent.invoker.v1.AddMethod" json:"method,omitempty"`
	Path                 string    `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{2}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddRequest) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

func (m *AddRequest) GetMethod() AddMethod {
	if m != nil {
		return m.Method
	}
	return AddMethod_UNKOWN
}

func (m *AddRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type AddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{3}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

type ListRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ManagedActivity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Runtime              string   `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Added                string   `protobuf:"bytes,3,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagedActivity) Reset()         { *m = ManagedActivity{} }
func (m *ManagedActivity) String() string { return proto.CompactTextString(m) }
func (*ManagedActivity) ProtoMessage()    {}
func (*ManagedActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{5}
}

func (m *ManagedActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedActivity.Unmarshal(m, b)
}
func (m *ManagedActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedActivity.Marshal(b, m, deterministic)
}
func (m *ManagedActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedActivity.Merge(m, src)
}
func (m *ManagedActivity) XXX_Size() int {
	return xxx_messageInfo_ManagedActivity.Size(m)
}
func (m *ManagedActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedActivity.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedActivity proto.InternalMessageInfo

func (m *ManagedActivity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ManagedActivity) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *ManagedActivity) GetAdded() string {
	if m != nil {
		return m.Added
	}
	return ""
}

type ListResponse struct {
	Activities           []*ManagedActivity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetActivities() []*ManagedActivity {
	if m != nil {
		return m.Activities
	}
	return nil
}

type RemoveRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ActName              string   `protobuf:"bytes,2,opt,name=actName,proto3" json:"actName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{7}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RemoveRequest) GetActName() string {
	if m != nil {
		return m.ActName
	}
	return ""
}

type RemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64215b76ff6c9221, []int{8}
}

func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("mee6aas.agent.invoker.v1.AddMethod", AddMethod_name, AddMethod_value)
	proto.RegisterType((*InvokeRequest)(nil), "mee6aas.agent.invoker.v1.InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "mee6aas.agent.invoker.v1.InvokeResponse")
	proto.RegisterType((*AddRequest)(nil), "mee6aas.agent.invoker.v1.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "mee6aas.agent.invoker.v1.AddResponse")
	proto.RegisterType((*ListRequest)(nil), "mee6aas.agent.invoker.v1.ListRequest")
	proto.RegisterType((*ManagedActivity)(nil), "mee6aas.agent.invoker.v1.ManagedActivity")
	proto.RegisterType((*ListResponse)(nil), "mee6aas.agent.invoker.v1.ListResponse")
	proto.RegisterType((*RemoveRequest)(nil), "mee6aas.agent.invoker.v1.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "mee6aas.agent.invoker.v1.RemoveResponse")
}

func init() { proto.RegisterFile("invoker.proto", fileDescriptor_64215b76ff6c9221) }

var fileDescriptor_64215b76ff6c9221 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0x6d, 0x3e, 0x6e, 0xae, 0x9d, 0x9a, 0x1a, 0x16, 0x91, 0xd0, 0xa7, 0xcb, 0xfa, 0x95, 0xeb,
	0x43, 0xa0, 0x15, 0x7c, 0xf1, 0x29, 0x15, 0x91, 0x62, 0xda, 0x42, 0xb0, 0x14, 0x85, 0x3e, 0xac,
	0xdd, 0xa5, 0x0d, 0x9a, 0xa4, 0x66, 0x37, 0x01, 0x7f, 0x87, 0xff, 0xd5, 0x67, 0xc9, 0x6e, 0x12,
	0x5b, 0xa1, 0xa9, 0xd0, 0xb7, 0x39, 0x3b, 0x33, 0x27, 0x67, 0xce, 0x0c, 0x01, 0x3b, 0x4e, 0xcb,
	0xec, 0x1b, 0xcb, 0xfd, 0x43, 0x9e, 0x89, 0x0c, 0xb9, 0x09, 0x63, 0x6f, 0x08, 0xe1, 0x3e, 0xd9,
	0xb1, 0x54, 0xf8, 0x4d, 0xb2, 0x1c, 0xe3, 0x35, 0xd8, 0x33, 0x89, 0x22, 0xf6, 0xa3, 0x60, 0x5c,
	0xa0, 0x11, 0x3c, 0x28, 0x38, 0xcb, 0x53, 0x92, 0x30, 0x57, 0xbb, 0xd3, 0xbc, 0x7e, 0xd4, 0x62,
	0xe4, 0xc2, 0x2d, 0xd9, 0x8a, 0x45, 0x95, 0xd2, 0x65, 0xaa, 0x81, 0xc8, 0x01, 0x83, 0xe4, 0x3b,
	0xd7, 0x90, 0xaf, 0x55, 0x88, 0x3d, 0x18, 0x36, 0xc4, 0xfc, 0x90, 0xa5, 0x9c, 0xa1, 0x27, 0x60,
	0xe5, 0x8c, 0x17, 0xdf, 0x45, 0xcd, 0x5b, 0x23, 0xfc, 0x4b, 0x03, 0x08, 0x28, 0xbd, 0x4e, 0xc0,
	0x5b, 0xb0, 0x12, 0x26, 0xf6, 0x19, 0x95, 0x1a, 0x86, 0x93, 0xa7, 0xfe, 0xb9, 0x91, 0xfd, 0x80,
	0xd2, 0xb9, 0x2c, 0x8d, 0xea, 0x16, 0x84, 0xc0, 0x3c, 0x10, 0xb1, 0x77, 0x4d, 0xc9, 0x29, 0x63,
	0x6c, 0xc3, 0x40, 0x8a, 0x52, 0xe2, 0xf1, 0x3d, 0x0c, 0xc2, 0x98, 0x8b, 0xff, 0x10, 0x89, 0x57,
	0xf0, 0x68, 0x4e, 0x52, 0xb2, 0x63, 0x34, 0xd8, 0x8a, 0xb8, 0x8c, 0xc5, 0xcf, 0xea, 0x03, 0x47,
	0xa5, 0x66, 0x33, 0x4b, 0x5e, 0xa4, 0x22, 0xfe, 0x3b, 0x4b, 0x0d, 0xd1, 0x63, 0xb8, 0x21, 0x94,
	0x32, 0x5a, 0xdb, 0xa9, 0x00, 0xfe, 0x0c, 0x0f, 0x95, 0x82, 0xda, 0xce, 0x19, 0x00, 0x51, 0xfc,
	0x31, 0xe3, 0xae, 0x76, 0x67, 0x78, 0x83, 0xc9, 0xfd, 0xf9, 0xa9, 0xff, 0x91, 0x14, 0x1d, 0x35,
	0xe3, 0xf7, 0x60, 0x47, 0x2c, 0xc9, 0xca, 0xeb, 0x8e, 0x00, 0x3b, 0x30, 0x6c, 0x68, 0x94, 0xc6,
	0x57, 0x3e, 0xf4, 0x5b, 0xb7, 0x11, 0x80, 0xb5, 0x5a, 0x7c, 0x5c, 0xae, 0x17, 0x4e, 0x0f, 0xf5,
	0xe1, 0x26, 0x5c, 0xbe, 0x0b, 0x42, 0x47, 0xab, 0x9e, 0x3f, 0x84, 0xcb, 0x69, 0x10, 0x3a, 0xfa,
	0xe4, 0xb7, 0x0e, 0xb7, 0xea, 0x6a, 0x72, 0xb4, 0x01, 0x4b, 0x85, 0xe8, 0xe5, 0xf9, 0xa9, 0x4e,
	0x6e, 0x77, 0xe4, 0x5d, 0x2e, 0xac, 0xd7, 0xd9, 0x43, 0x9f, 0xc0, 0x08, 0x28, 0x45, 0xcf, 0x3a,
	0xef, 0xa4, 0x21, 0x7e, 0x7e, 0xa1, 0xaa, 0x65, 0x5d, 0x83, 0x59, 0x2d, 0x09, 0x75, 0x34, 0x1c,
	0x9d, 0xd1, 0xe8, 0xc5, 0xa5, 0xb2, 0x96, 0x78, 0x03, 0x96, 0xf2, 0xb6, 0xcb, 0x8d, 0x93, 0x25,
	0x76, 0xb9, 0x71, 0xba, 0x26, 0xdc, 0x9b, 0x9a, 0x5f, 0xf4, 0x72, 0xfc, 0xd5, 0x92, 0x7f, 0x8b,
	0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0x3f, 0x07, 0xe0, 0x3e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvokerClient is the client API for Invoker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvokerClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type invokerClient struct {
	cc *grpc.ClientConn
}

func NewInvokerClient(cc *grpc.ClientConn) InvokerClient {
	return &invokerClient{cc}
}

func (c *invokerClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokerClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokerClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokerClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invoker.v1.Invoker/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokerServer is the server API for Invoker service.
type InvokerServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

// UnimplementedInvokerServer can be embedded to have forward compatible implementations.
type UnimplementedInvokerServer struct {
}

func (*UnimplementedInvokerServer) Invoke(ctx context.Context, req *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (*UnimplementedInvokerServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedInvokerServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedInvokerServer) Remove(ctx context.Context, req *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterInvokerServer(s *grpc.Server, srv InvokerServer) {
	s.RegisterService(&_Invoker_serviceDesc, srv)
}

func _Invoker_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoker_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoker_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invoker_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokerServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invoker.v1.Invoker/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokerServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invoker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mee6aas.agent.invoker.v1.Invoker",
	HandlerType: (*InvokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _Invoker_Invoke_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Invoker_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Invoker_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Invoker_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoker.proto",
}
