// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invokee.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRequest) Reset()         { *m = ListenRequest{} }
func (m *ListenRequest) String() string { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()    {}
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{0}
}

func (m *ListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRequest.Unmarshal(m, b)
}
func (m *ListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRequest.Marshal(b, m, deterministic)
}
func (m *ListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRequest.Merge(m, src)
}
func (m *ListenRequest) XXX_Size() int {
	return xxx_messageInfo_ListenRequest.Size(m)
}
func (m *ListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRequest proto.InternalMessageInfo

type Task struct {
	Arg                  string   `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

func init() {
	proto.RegisterType((*ListenRequest)(nil), "mee6aas.agent.invokee.v1.ListenRequest")
	proto.RegisterType((*Task)(nil), "mee6aas.agent.invokee.v1.Task")
}

func init() { proto.RegisterFile("invokee.proto", fileDescriptor_6e11f4dbf517a09d) }

var fileDescriptor_6e11f4dbf517a09d = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcc, 0x2b, 0xcb,
	0xcf, 0x4e, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xc8, 0x4d, 0x4d, 0x35, 0x4b,
	0x4c, 0x2c, 0xd6, 0x4b, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x83, 0x49, 0x96, 0x19, 0x2a, 0xf1, 0x73,
	0xf1, 0xfa, 0x64, 0x16, 0x97, 0xa4, 0xe6, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x49,
	0x70, 0xb1, 0x84, 0x24, 0x16, 0x67, 0x0b, 0x09, 0x70, 0x31, 0x27, 0x16, 0xa5, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x46, 0x09, 0x5c, 0xec, 0x9e, 0x10, 0x8d, 0x42, 0xa1, 0x5c,
	0x6c, 0x10, 0x5d, 0x42, 0xea, 0x7a, 0xb8, 0x8c, 0xd6, 0x43, 0x31, 0x57, 0x4a, 0x0e, 0xb7, 0x42,
	0x90, 0x7d, 0x4a, 0x0c, 0x06, 0x8c, 0x4e, 0x2c, 0x51, 0x4c, 0x65, 0x86, 0x49, 0x6c, 0x60, 0x37,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x19, 0xb7, 0xac, 0xc4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvokeeClient is the client API for Invokee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvokeeClient interface {
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Invokee_ListenClient, error)
}

type invokeeClient struct {
	cc *grpc.ClientConn
}

func NewInvokeeClient(cc *grpc.ClientConn) InvokeeClient {
	return &invokeeClient{cc}
}

func (c *invokeeClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Invokee_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Invokee_serviceDesc.Streams[0], "/mee6aas.agent.invokee.v1.Invokee/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &invokeeListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Invokee_ListenClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type invokeeListenClient struct {
	grpc.ClientStream
}

func (x *invokeeListenClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InvokeeServer is the server API for Invokee service.
type InvokeeServer interface {
	Listen(*ListenRequest, Invokee_ListenServer) error
}

// UnimplementedInvokeeServer can be embedded to have forward compatible implementations.
type UnimplementedInvokeeServer struct {
}

func (*UnimplementedInvokeeServer) Listen(req *ListenRequest, srv Invokee_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}

func RegisterInvokeeServer(s *grpc.Server, srv InvokeeServer) {
	s.RegisterService(&_Invokee_serviceDesc, srv)
}

func _Invokee_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvokeeServer).Listen(m, &invokeeListenServer{stream})
}

type Invokee_ListenServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type invokeeListenServer struct {
	grpc.ServerStream
}

func (x *invokeeListenServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

var _Invokee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mee6aas.agent.invokee.v1.Invokee",
	HandlerType: (*InvokeeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Invokee_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "invokee.proto",
}
