// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invokee.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskType int32

const (
	TaskType_UNKNOWN TaskType = 0
	TaskType_LOAD    TaskType = 1
	TaskType_INVOKE  TaskType = 2
)

var TaskType_name = map[int32]string{
	0: "UNKNOWN",
	1: "LOAD",
	2: "INVOKE",
}

var TaskType_value = map[string]int32{
	"UNKNOWN": 0,
	"LOAD":    1,
	"INVOKE":  2,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}

func (TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{0}
}

type ListenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRequest) Reset()         { *m = ListenRequest{} }
func (m *ListenRequest) String() string { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()    {}
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{0}
}

func (m *ListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRequest.Unmarshal(m, b)
}
func (m *ListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRequest.Marshal(b, m, deterministic)
}
func (m *ListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRequest.Merge(m, src)
}
func (m *ListenRequest) XXX_Size() int {
	return xxx_messageInfo_ListenRequest.Size(m)
}
func (m *ListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRequest proto.InternalMessageInfo

type Task struct {
	Type                 TaskType `protobuf:"varint,1,opt,name=type,proto3,enum=mee6aas.agent.invokee.v1.TaskType" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Arg                  string   `protobuf:"bytes,3,opt,name=arg,proto3" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{1}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetType() TaskType {
	if m != nil {
		return m.Type
	}
	return TaskType_UNKNOWN
}

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetArg() string {
	if m != nil {
		return m.Arg
	}
	return ""
}

type ReportRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	IsError              bool     `protobuf:"varint,3,opt,name=isError,proto3" json:"isError,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{2}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReportRequest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ReportRequest) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

type ReportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{3}
}

func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

type HandoverRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandoverRequest) Reset()         { *m = HandoverRequest{} }
func (m *HandoverRequest) String() string { return proto.CompactTextString(m) }
func (*HandoverRequest) ProtoMessage()    {}
func (*HandoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{4}
}

func (m *HandoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoverRequest.Unmarshal(m, b)
}
func (m *HandoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoverRequest.Marshal(b, m, deterministic)
}
func (m *HandoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoverRequest.Merge(m, src)
}
func (m *HandoverRequest) XXX_Size() int {
	return xxx_messageInfo_HandoverRequest.Size(m)
}
func (m *HandoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandoverRequest proto.InternalMessageInfo

type HandoverResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandoverResponse) Reset()         { *m = HandoverResponse{} }
func (m *HandoverResponse) String() string { return proto.CompactTextString(m) }
func (*HandoverResponse) ProtoMessage()    {}
func (*HandoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e11f4dbf517a09d, []int{5}
}

func (m *HandoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandoverResponse.Unmarshal(m, b)
}
func (m *HandoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandoverResponse.Marshal(b, m, deterministic)
}
func (m *HandoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandoverResponse.Merge(m, src)
}
func (m *HandoverResponse) XXX_Size() int {
	return xxx_messageInfo_HandoverResponse.Size(m)
}
func (m *HandoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandoverResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("mee6aas.agent.invokee.v1.TaskType", TaskType_name, TaskType_value)
	proto.RegisterType((*ListenRequest)(nil), "mee6aas.agent.invokee.v1.ListenRequest")
	proto.RegisterType((*Task)(nil), "mee6aas.agent.invokee.v1.Task")
	proto.RegisterType((*ReportRequest)(nil), "mee6aas.agent.invokee.v1.ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "mee6aas.agent.invokee.v1.ReportResponse")
	proto.RegisterType((*HandoverRequest)(nil), "mee6aas.agent.invokee.v1.HandoverRequest")
	proto.RegisterType((*HandoverResponse)(nil), "mee6aas.agent.invokee.v1.HandoverResponse")
}

func init() { proto.RegisterFile("invokee.proto", fileDescriptor_6e11f4dbf517a09d) }

var fileDescriptor_6e11f4dbf517a09d = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x6b, 0xea, 0x40,
	0x10, 0x85, 0x4d, 0x0c, 0x31, 0x77, 0x2e, 0x6a, 0xee, 0x3c, 0x5c, 0x82, 0x0f, 0x45, 0xf6, 0xa5,
	0x56, 0x68, 0xa8, 0x16, 0x7c, 0x6f, 0xa9, 0x50, 0x51, 0x22, 0x0d, 0xda, 0x42, 0xa1, 0xd0, 0xb4,
	0x0e, 0x12, 0x6c, 0xb3, 0xe9, 0xee, 0x1a, 0xf0, 0xff, 0xf4, 0x87, 0x16, 0x93, 0x6c, 0x8b, 0x05,
	0x6d, 0xdf, 0x76, 0x66, 0xcf, 0x9c, 0xd9, 0xf3, 0xb1, 0x50, 0x8f, 0x93, 0x8c, 0xaf, 0x88, 0xfc,
	0x54, 0x70, 0xc5, 0xd1, 0x7b, 0x25, 0x1a, 0x44, 0x91, 0xf4, 0xa3, 0x25, 0x25, 0xca, 0xd7, 0x97,
	0x59, 0x8f, 0x35, 0xa1, 0x3e, 0x89, 0xa5, 0xa2, 0x24, 0xa4, 0xb7, 0x35, 0x49, 0xc5, 0x1e, 0xc1,
	0x9a, 0x45, 0x72, 0x85, 0x03, 0xb0, 0xd4, 0x26, 0x25, 0xcf, 0x68, 0x1b, 0x9d, 0x46, 0x9f, 0xf9,
	0xfb, 0x1c, 0xfc, 0xad, 0x7a, 0xb6, 0x49, 0x29, 0xcc, 0xf5, 0xd8, 0x00, 0x33, 0x5e, 0x78, 0x66,
	0xdb, 0xe8, 0xfc, 0x09, 0xcd, 0x78, 0x81, 0x2e, 0x54, 0x23, 0xb1, 0xf4, 0xaa, 0x79, 0x63, 0x7b,
	0x64, 0x37, 0x50, 0x0f, 0x29, 0xe5, 0x42, 0x95, 0x2b, 0xcb, 0x11, 0xe3, 0x73, 0xe4, 0x3f, 0xd8,
	0x82, 0xe4, 0xfa, 0x45, 0x95, 0x36, 0x65, 0x85, 0x1e, 0xd4, 0x62, 0x39, 0x14, 0x82, 0x8b, 0xdc,
	0xce, 0x09, 0x75, 0xc9, 0x5c, 0x68, 0x68, 0x4b, 0x99, 0xf2, 0x44, 0x12, 0xfb, 0x07, 0xcd, 0xeb,
	0x28, 0x59, 0xf0, 0x8c, 0x84, 0x4e, 0x86, 0xe0, 0x7e, 0xb5, 0x0a, 0x59, 0xf7, 0x14, 0x1c, 0xfd,
	0x7e, 0xfc, 0x0b, 0xb5, 0x79, 0x30, 0x0e, 0xa6, 0x77, 0x81, 0x5b, 0x41, 0x07, 0xac, 0xc9, 0xf4,
	0xe2, 0xca, 0x35, 0x10, 0xc0, 0x1e, 0x05, 0xb7, 0xd3, 0xf1, 0xd0, 0x35, 0xfb, 0xef, 0x26, 0xd4,
	0x46, 0x45, 0x74, 0x9c, 0x83, 0x5d, 0x90, 0xc3, 0xe3, 0xfd, 0x70, 0x76, 0xd8, 0xb6, 0x8e, 0x0e,
	0x53, 0x64, 0x95, 0x33, 0x03, 0x1f, 0xc0, 0x2e, 0xa2, 0x1c, 0xb2, 0xdd, 0xe1, 0xd7, 0xea, 0xfc,
	0x2c, 0x2c, 0xa9, 0x54, 0xf0, 0x19, 0x1c, 0x0d, 0x01, 0x4f, 0xf6, 0xcf, 0x7d, 0x63, 0xd7, 0xea,
	0xfe, 0x46, 0xaa, 0x97, 0x5c, 0x5a, 0xf7, 0x66, 0xd6, 0x7b, 0xb2, 0xf3, 0xbf, 0x77, 0xfe, 0x11,
	0x00, 0x00, 0xff, 0xff, 0x61, 0x00, 0x7b, 0xfe, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvokeeClient is the client API for Invokee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvokeeClient interface {
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Invokee_ListenClient, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	Handover(ctx context.Context, in *HandoverRequest, opts ...grpc.CallOption) (*HandoverResponse, error)
}

type invokeeClient struct {
	cc *grpc.ClientConn
}

func NewInvokeeClient(cc *grpc.ClientConn) InvokeeClient {
	return &invokeeClient{cc}
}

func (c *invokeeClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (Invokee_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Invokee_serviceDesc.Streams[0], "/mee6aas.agent.invokee.v1.Invokee/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &invokeeListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Invokee_ListenClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type invokeeListenClient struct {
	grpc.ClientStream
}

func (x *invokeeListenClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invokeeClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invokee.v1.Invokee/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invokeeClient) Handover(ctx context.Context, in *HandoverRequest, opts ...grpc.CallOption) (*HandoverResponse, error) {
	out := new(HandoverResponse)
	err := c.cc.Invoke(ctx, "/mee6aas.agent.invokee.v1.Invokee/Handover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvokeeServer is the server API for Invokee service.
type InvokeeServer interface {
	Listen(*ListenRequest, Invokee_ListenServer) error
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	Handover(context.Context, *HandoverRequest) (*HandoverResponse, error)
}

// UnimplementedInvokeeServer can be embedded to have forward compatible implementations.
type UnimplementedInvokeeServer struct {
}

func (*UnimplementedInvokeeServer) Listen(req *ListenRequest, srv Invokee_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (*UnimplementedInvokeeServer) Report(ctx context.Context, req *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (*UnimplementedInvokeeServer) Handover(ctx context.Context, req *HandoverRequest) (*HandoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handover not implemented")
}

func RegisterInvokeeServer(s *grpc.Server, srv InvokeeServer) {
	s.RegisterService(&_Invokee_serviceDesc, srv)
}

func _Invokee_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvokeeServer).Listen(m, &invokeeListenServer{stream})
}

type Invokee_ListenServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type invokeeListenServer struct {
	grpc.ServerStream
}

func (x *invokeeListenServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func _Invokee_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokeeServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invokee.v1.Invokee/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokeeServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invokee_Handover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvokeeServer).Handover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mee6aas.agent.invokee.v1.Invokee/Handover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvokeeServer).Handover(ctx, req.(*HandoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invokee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mee6aas.agent.invokee.v1.Invokee",
	HandlerType: (*InvokeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Invokee_Report_Handler,
		},
		{
			MethodName: "Handover",
			Handler:    _Invokee_Handover_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Invokee_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "invokee.proto",
}
